### ISSUE TITLE
WIP: Add support for resources in namespace packages - [opened]

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#195]
In GitLab by @FFY00 on Oct 20, 2020, 19:20

_Merges namespace-resources -> master_

- [X] `imporlib_resources.open_binary` and methods that build on top of it
- [ ] `imporlib_resources.contents`

**Comment by jaraco** [comment]
In GitLab by @FFY00 on Oct 20, 2020, 19:20

added 2 commits

<ul><li>1f2d30ce - add support for namespace packages in open_binary</li><li>163f46a2 - tests: remove tests making sure namespace packages can&#39;t have resources</li></ul>

[Compare with previous version](/python-devs/importlib_resources/-/merge_requests/109/diffs?diff_id=119393088&start_sha=116b1417b57591610f4b37943fe2e1661a2c72fa)

**Comment by jaraco** [comment]
In GitLab by @FFY00 on Oct 20, 2020, 19:22

The hard part now is to add support in `imporlib_resources.contents` as it requires us to export a `submodule_search_locations` based resource reader in `LoaderAdapter`.

Writing a `submodule_search_locations` based resource loader requires us to have a `Transversable` class that can multiplex multiple paths.

**Comment by jaraco** [comment]
In GitLab by @FFY00 on Oct 21, 2020, 06:56

added 3 commits

<ul><li>3aadd621 - add support for namespace packages in open_binary</li><li>fd160322 - tests: remove tests making sure namespace packages can&#39;t have resources</li><li>2ea54684 - add support for namespace modules in contents</li></ul>

[Compare with previous version](/python-devs/importlib_resources/-/merge_requests/109/diffs?diff_id=119499818&start_sha=163f46a26fa8edf2b371591b2682c1ec42f8abf1)

**Comment by jaraco** [comment]
In GitLab by @FFY00 on Oct 21, 2020, 07:01

added 1 commit

<ul><li>05e22686 - add support for namespace modules in contents</li></ul>

[Compare with previous version](/python-devs/importlib_resources/-/merge_requests/109/diffs?diff_id=119500983&start_sha=2ea546844ac3a13dca42e7f1ba8b95cfa55bcaf5)

**Comment by jaraco** [comment]
In GitLab by @FFY00 on Oct 21, 2020, 07:02

added 1 commit

<ul><li>1eb80820 - add support for namespace modules in contents</li></ul>

[Compare with previous version](/python-devs/importlib_resources/-/merge_requests/109/diffs?diff_id=119501247&start_sha=05e2268627f462aebf71ce3bedd15e451a5f3fb7)

**Comment by FFY00** [comment]
This was a MR, can be closed.
