### ISSUE TITLE
Library has dropped support for py27 and py35 and should probably say so

### ISSUE THREAD

**Issue by ajkavanagh** [python/importlib_resources#207]
The README.rst for this module says it's support py27 and py34 to py38.  However, it has recently dropped support for py35 (as of 3.3 I believe, it's hard to tell as there are no release notes) and probably that means dropped support for py27 and py34 at some earlier date.  Yet, the README and the blurb on PyPi leads you to believe that the library still supports it.  Certainly made my debugging a bit more difficult.

**Comment by ajkavanagh** [comment]
Actually, it appears the master branch says the right thing, but the released versions don't.  This sometimes happens - I've done the "update after release thing too".  Anyway, leaving this here just in case another point release is done prior for 3.3 to fix the docs?

**Comment by FFY00** [comment]
Yes, this changed in #205. Unfortunately, we can't fix prior versions.

**Comment by jaraco** [comment]
I've push v3.3.1, from main, so it should include the change when released.
