### ISSUE TITLE
as_file() is undocumented

### ISSUE THREAD

**Issue by SyntaxColoring** [python/importlib_resources#210]
I'm not sure if this issue belong here or on the CPython bug tracker, but...

The useful `as_file()` function only appears in [this example on importlib-resources.readthedocs.io](https://importlib-resources.readthedocs.io/en/latest/using.html#file-system-or-zip-file):

```python
from importlib_resources import files, as_file

source = files(email.tests.data).joinpath('message.eml')
with as_file(source) as eml:
    third_party_api_requiring_file_system_path(eml)
```

importlib-resources.readthedocs.io says to defer to docs.python.org for API reference documentation. But I couldn't find any mention of `as_file()` there, either.

I would expect `as_file()` to be mentioned somewhere on https://docs.python.org/3/library/importlib.html.

**Comment by jaraco** [comment]
Unfortunately, none of the docs are synced between these two projects. Probably the documentation for that function should be added to CPython. Thanks for reporting, though. I'll leave this open until we have a bug report in bpo, which I can file.

**Comment by jaraco** [comment]
Filed [43644](https://bugs.python.org/issue43644) downstream.
