### ISSUE TITLE
readers.MultiplexedPath.name is not a property

### ISSUE THREAD

**Issue by ap--** [python/importlib_resources#216]
Hi @jaraco 

I found this bug, and already opened an issue for cpython here: https://bugs.python.org/issue43643

If it helps I can prepare a pull request.

Cheers,
Andreas

**Comment by jaraco** [comment]
Thanks for the report and for cross-linking. Yes, PR would be nice. If you make it here, it's easier for me to merge into CPython.

**Comment by FFY00** [comment]
Uh, I wonder why this wasn't caught. Perhaps our `runtime_checkable` is broken?
