### ISSUE TITLE
Duplicated `TraversableResourcesLoader` and `wrap_spec`

### ISSUE THREAD

**Issue by FFY00** [python/importlib_resources#227]
8207434d94bff5aa4e78f1c6b93108eb72f2d112 seems to have mistakenly added some `TraversableResourcesLoader` and `wrap_spec` implementations to the `_adapters` module. Objects with the same name and better implementation already exist in `_compat`, and it seems to me these ones are leftover from a previous code redesign. Can you confirm @jaraco?

Waiting on #221 getting resolved to submit a PR as it will conflict.

**Comment by jaraco** [comment]
I encountered this confusion as well while getting back up-to-speed on this project.

The key difference between the implementation in `_adapters` and `_compat` is that `_adapters.*` is used in CPython 3.10, where the FileReader and ZipReader and NamespaceReaders exist natively for their respective loaders. `_compat` is used in the backport only and exists to support older Pythons where those loaders don't provide the native implementations presenting `TraversableResources`.

I can update the docstrings in those modules to reflect this need.

**Comment by FFY00** [comment]
That clarifies it, thanks!
