### ISSUE TITLE
API reference missing in documentation

### ISSUE THREAD

**Issue by FFY00** [python/importlib_resources#245]
It seems like the API reference is currently broken and missing in the documentation.

I was trying to link to this module using intersphinx but it fails, likely because of this.
```
WARNING: py:mod reference target not found: importlib_resources
```

**Comment by jaraco** [comment]
I don't believe this package provides an API reference. This package was written before there was a reliable sync between it and its cpython counterpart. As a result, the documentation diverged and this package only has a few bits about usage and migration.

What's the value in linking to this API versus importlib.resources?

**Comment by FFY00** [comment]
> I don't believe this package provides an API reference. This package was written before there was a reliable sync between it and its cpython counterpart. As a result, the documentation diverged and this package only has a few bits about usage and migration.

Well, there is https://github.com/python/importlib_resources/blob/main/docs/index.rst.

> What's the value in linking to this API versus importlib.resources?

See how I wanted to use it.

https://meson-python.readthedocs.io/en/latest/#no-data

**Comment by jaraco** [comment]
I see. So maybe just link to https://pypi.org/project/importlib_resources or https://importlib-resources.readthedocs.io?

**Comment by jaraco** [comment]
Maybe see importlib_metadata supplies API docs. There were recently some complaints on that project because it supplied API docs but the Python version did not, so keep that in mind as a potential issue.
