### ISSUE TITLE
Missing setup.py in the 5.6.0 release

### ISSUE THREAD

**Issue by tylau0** [python/importlib_resources#247]
I see that the 5.6.0 release is broken as setup.py is no longer there. It was there in the 5.4.0 release. 
The file gets deleted in the following commit. https://github.com/python/importlib_resources/commit/7e01b721c237ee4947e3b9d6e56bb03a028f3f6a.
The comment there says the file is not no longer necessary.
I find some articles that sugguest the same view, e.g. https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
However it might break some existing build code that are built with the 5.4.0 release and assume the presence of setup.py. 
May I suggest the file to be kept?
Thanks.

**Comment by jaraco** [comment]
That same commit exists in all of the packages I maintain based on [jaraco/skeleton](/jaraco/skeleton).

Environments shouldn't be requiring the `setup.py` file. Such environments are already broken for packages that don't supply a setup.py, such as flit projects. These environments are rare and if they need to be supported, they should use older versions of packages or provide their own compatibility layer to inject a boilerplate setup.py. Keeping copies of these boilerplate setup.py files in all of the projects will only encourage this antipattern.

Is there a reason that approach can't work for your use-case?

**Comment by jaraco** [comment]
I'm closing as this change was intentional. Feel free to follow up with more information and I can reconsider.
