### ISSUE TITLE
Expand usage guide to illustrate namespace package usage.

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#262]
> Do the importlib.resources documentation (or maybe packaging guides) discuss any of these use cases and best practices?

I just reviewed [the docs](https://docs.python.org/3/library/importlib.html#module-importlib.resources), and they are pretty sparse about the purpose of the API. It does link to the ["using" guide](https://importlib-resources.readthedocs.io/en/latest/using.html), and that does seem like it might be an appropriate place to publish that information.

_Originally posted by @jaraco in https://github.com/python/importlib_resources/issues/68#issuecomment-1199476054_

**Comment by jaraco** [comment]
cc @warsaw

**Comment by ckp95** [comment]
yeah I went around in circles for hours today trying to solve a problem with namespace packages. I didn't realize the fix was in here because the docs didn't mention it.
