### ISSUE TITLE
MultiplexedPath only traverses first directory

### ISSUE THREAD

**Issue by jooste** [python/importlib_resources#265]
I ran into the following issue while trying to update my MultiplexedPath example in #264 to the current structure. Let's say you have the following path structure:
```
data01
  |_x

data02
  |_x
    |_y
      |_z.txt
```
If you combine `data01` and `data02` in a`MultiplexedPath`, `data01/x` will make it impossible to find `data02/x/y`, see the following example:
```python
from importlib_resources.readers import MultiplexedPath

p = MultiplexedPath('data01', 'data02')
```
In this case if you do:
```python
print(p / 'x/y')
```
this will give `data01/x/y` instead of `data02/x/y`, and
```python
for f in (p / 'x/y').iterdir():
    print(f)
```
will raise a `FileNotFoundError`.

The reason for this is that in `Traversable.joinpath()`, only the first path segment is used to search for a match:
```python
names = itertools.chain.from_iterable(
    path.parts for path in map(pathlib.PurePosixPath, descendants)
)
target = next(names)
```
and then, only the first match is returned:
```python
matches = (
    traversable for traversable in self.iterdir() if traversable.name == target
)
try:
    match = next(matches)
```
The solution to this problem could be related to the suggestion in #264, unless returning `MultiplexedPath`s isn't the desired behaviour of `MultiplexedPath.joinpath()`.

**Comment by jaraco** [comment]
Agreed, `MultiplexedPath` is meant to honor all paths, recursively. Your suggestion looks approximately correct.

Do you have any interest in developing the fix (as a pull request), including tests to capture the missed expectation?

**Comment by jooste** [comment]
Sure! My only worry was that my implementation is based on a previous structure of `MultiplexedPath`. But if it looks ok I'll work on making it into a PR.
