### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by stephenfrench9** [python/importlib_resources#273]
I have been searching the documentation for information about which versions of `importlib_resources` should be used for a given version of python, but have not found this information. I have questions like, can I use `v5.10.0` with python 3.7? with python 2.7?

Can you point me in the right direction?

**Comment by FFY00** [comment]
I wouldn't worry much about the version, unless you need specific features.

> can I use `v5.10.0` with python 3.7?

Yes.

https://github.com/python/importlib_resources/blob/6d64beb916bf6572f39973ea32b64268b2a4274a/setup.cfg#L20

> with python 2.7?

`pip2 install importlib_resources` installs `importlib_resources` 3.3.1 on my system, so I think that should be the latest version supporting Python 2.

**Comment by jaraco** [comment]
To elaborate on what FFY00 said, you can go to the [project page on PyPI](https://pypi.org/project/importlib-resources/) to see the supported python versions. By default, it shows the supported Python versions for the latest release (`>= 3.7`), but you can either use pip (as FFY00 did) on an older Python to see what version gets downloaded or look through the different releases in the release history to see which versions declare support for which Pythons.

Please feel free to comment or file a new issue if that didn't fully answer the question.
