### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by sunpoet** [python/importlib_resources#285]
According to the classifiers in setup.cfg, it is licensed under Apache Software License.
But the content of LICENSE file is MIT License.

Which one is correct?
Thanks.

**Comment by jaraco** [comment]
Great question. Thanks for reporting. I double-checked and this issue does not apply to importlib_metadata.

It looks like it was inadvertently reverted to the upstream default license in 8de19cf901dece8c587e2d072a687a7acf81d49e.
