### ISSUE TITLE
Make functional module private

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#305]
Should this module be private or should importing from `importlib_resources.functional` be allowed?

_Originally posted by @layday in https://github.com/python/importlib_resources/pull/303#discussion_r1534636317_

**Comment by FFY00** [comment]
I don't think it should be allowed, that's more exposed API without a real need IMO.

**Comment by layday** [comment]
This appears to have already been done in the stdlib BTW: https://github.com/python/cpython/blob/main/Lib/importlib/resources/_functional.py. I don't know if any other differences exist.
