### ISSUE TITLE
Drop support for Python 3.8 (and older)?

### ISSUE THREAD

**Issue by Hedda** [python/importlib_resources#316]
Python 3.8 is currently receiving only security updates and that will end next month, so time to drop support for Python 3.8?

That it, should now require at least Python 3.9 or later?

But note that even Python 3.9 is EoL (End-of-Life) now and will stop receiving all updates (including security) next year so you ideally would want to be on at least Python 3.10 or preferably Python 3.11

Regardless, it would be best to push your to the highest version of Python possible.

**Comment by jaraco** [comment]
Hi Hedda. This project follows the [skeleton](https://blog.jaraco.com/skeleton) methodology, so it will get that treatment when other projects do. I'm hoping to eventually port this project and others to the [coherent system](https://bit.ly/coherent-system), which has a feature to _automatically_ drop support for sunset Python versions.
