### ISSUE TITLE
zipimporter breaks in python3.5/python3.6 within a zipapp when zipapp call path is not absolute

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#75]
In GitLab by @jokerjokerer on Jan 14, 2020, 12:48

Within a zipapp the loaders archive path will be exactly the path passed on the caller side. So for:

```
py -3.5 tasks/virtualenv.pyz
```

the ``zipimporter`` archive path will be ``tasks/virtualenv.py``.  

https://gitlab.com/python-devs/importlib_resources/blob/1.0.2/importlib_resources/_py3.py#L83 sets the resource path always absolute. The logic for the zipimporter seems to care about this discrepancy (https://github.com/python/cpython/blob/v3.5.9/Modules/zipimport.c#L1131) as only paths that are starting with ``loader.archive`` will be returned. 

For example for resource ``tasks/virtualenv.py/a.data``:
- fails absolute format ``/w/tasks/virtualenv.py/a.data``
- succeeds ``tasks/virtualenv.py/a.data``
- succeeds ``a.data``

The current code returns the first format though. Shouldn't we normalize paths relative to the archive at https://gitlab.com/python-devs/importlib_resources/blob/1.0.2/importlib_resources/_py3.py#L93?

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Jan 14, 2020, 12:48

changed title from **zipimporter breaks in python3.5/python3.6 within a zipapp when zipapp path is not absolute** to **zipimporter breaks in python3.5/python3.6 within a zipapp when zipapp {+call +}path is not absolute**

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Jan 15, 2020, 14:03

Based on your specificity in the title I assume this doesn't affect 3.7 or 3.8?

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Jan 15, 2020, 14:49

I've been using there the standard library variant and that didn't manifest the issue 🤔 not sure if because that fixed the issue or moving the zipimporter to python from c caused the fix.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Jan 15, 2020, 20:02

It's possible the zipimporter rewrite fixed it and that's why the stdlib isn't affected.

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Jan 16, 2020, 02:34

It is 👍 but that still leaves python 3.5/3.6 without a solution at the moment 🤔 and probably 3.4 too, though not supported 👍

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Jan 17, 2020, 15:31

@jokerjokerer  very true. I was just trying to scope it to determine its urgency (and honestly how much I would personally care which unfortunately for you is "not much" since I don't use either of those versions anymore :grin: ).

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Jan 17, 2020, 16:51

This breaks virtualenv zipapp at the moment. So I'm not expecting you to do the work, but would need someone to agree on solution, me making the change; and the accepting and releasing it if possible (considering those two pythons are still supported upstream).

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Jan 20, 2020, 17:03

What does Python 3.7 and 3.8 return? My guess is your middle option.

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Feb 8, 2020, 06:43

So how can we move ahead with this? the release of virtualenv on Monday will make this more painful fo the users https://github.com/pypa/virtualenv/issues/1543 on

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Feb 22, 2020, 12:44

@brettcannon ping on this

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Feb 27, 2020, 14:02

@jaraco and @warsaw has already taken this project well past where Barry and I started it, so they are the ones in a position to try and fix this bug. :smile:

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 27, 2020, 14:36

And huge kudos to @jaraco who's taken it even farther than me!

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Feb 29, 2020, 02:25

So @jaraco the way I see it the ball is in your court, 🤔 Can you chim in to unblock this?

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Mar 5, 2020, 03:16

Ping :cry:

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 5, 2020, 08:55

I looked into this briefly and don’t have any insight. Was a solution proposed? Has a test been written?

**Comment by jaraco** [comment]
In GitLab by @jokerjokerer on Mar 5, 2020, 10:25

Something along the lines of normalizing the path before loading the resource is my idea 👍can write a test and implementation if you agree 👍

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 13:40

Yes, after reviewing this again, I suspect your proposed approach is close if not exactly what's needed. Please proceed with drafting a fix.

**Comment by jaraco** [comment]
@gaborbernat Are you still interested in working on this? Given that Python 3.6 only has about 7 months left of life, perhaps it's not worth fixing at this point?

**Comment by gaborbernat** [comment]
virtualenv support is 25 months still to go, but this is very low on my priority list, but I still use the ticket to point users to the issue when they run into this.

**Comment by jaraco** [comment]
This project is very likely to drop support for Python 3.6 in the coming month or two. I'd accept a patch to support the deficiency, but until that time, I'm closing this issue.
